### ISSUE TITLE
System.Text.Json should replace Newtonsoft.Json

### ISSUE THREAD

**Issue by hawkerm** [milanm/DotNet-Developer-Roadmap#5]
[System.Text.Json](https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/overview) is built-in to .NET now (and is available as a package otherwise). Should probably be recommended learning over the older Newtonsoft.Json package.

Article to link to for learning how to migrate: https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft

**Comment by milanm** [comment]
Yes, I agree! Will update. Thanks!

**Comment by milanm** [comment]
Fixed
